image: node:9.11.1

pages:
  cache:
    paths:
    - node_modules/ # ª∫¥Ê node_modules£¨º”ÀŸ±‡“Î

  script:
  - npm install
  - npm run docs:build
  artifacts:
    paths:
    - public
  only:
  - master